# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcMinOverlap <- function(seq, meanWidth) {
    .Call(`_RealReadSim_calcMinOverlap`, seq, meanWidth)
}

getCoverage <- function(pos, width, length) {
    .Call(`_RealReadSim_getCoverage`, pos, width, length)
}

evalCoverage <- function(pos, width, length, minOverlap, minContigLength) {
    .Call(`_RealReadSim_evalCoverage`, pos, width, length, minOverlap, minContigLength)
}

getIdenticalSeqs <- function(starts1, ends1, starts2, ends2, minL = 0L) {
    .Call(`_RealReadSim_getIdenticalSeqs`, starts1, ends1, starts2, ends2, minL)
}

sequenceToFastaReads <- function(starts, sequence, meanWidth, newFasta, nameTag) {
    .Call(`_RealReadSim_sequenceToFastaReads`, starts, sequence, meanWidth, newFasta, nameTag)
}

